import Head from 'next/head'
import { Inter } from '@next/font/google'
import Blogcard from "components/Blogcard"

import { GraphQLClient ,gql } from "graphql-request"
import Navbar from "components/Navbar"
const inter = Inter({ subsets: ['latin'] })


const graphcms = new GraphQLClient("https://api-ap-south-1.hygraph.com/v2/cldiict2a21gy01uq77a0go4n/master");


const QUERY = gql`{
 
    posts(orderBy:createdAt_DESC){
    title  
    cover{url}
    updatedBy {
      picture
      name
    }
    id
    datePublished
    slug

}

}`;

export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return{
    props:{
      posts,
    },
  };
}

export default function Home({posts}) {

    

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
      <Navbar/>
      <main className="flex py-20 justify-center bg-black">
      <div className="flex flex-col gap-5 ">
        {posts.map((post) =>
          <Blogcard 
          title={post.title}
          coverphoto={post.cover}
          key={post.id}
          datePublished={post.datePublished}
          slug={post.slug}
          owner={post.updatedBy}
           /> 
        )}
        </div>
      </main>
      </>
    </>
  )
}
